"""Add password and role_id to user, add role table

Revision ID: d58f4042a850
Revises: bc1c970a3eed
Create Date: 2026-08-27 16:18:06.042298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58f4042a850'
down_revision = 'bc1c970a3eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
